alias -g G='| grep'
alias -g GV='| grep -v'
alias -g L='| less'
alias -g LL="2>&1 | less"
alias -g C='| wc -l'
alias -g S='| sort'
alias -g H='| head'
alias -g T='| tail'
alias -g N="> /dev/null"
alias -g NN="> /dev/null 2>&1"
alias -g NE="2> /dev/null"
