set nocompatible

"Pathogen
execute pathogen#infect()

"Syntastic
let g:syntastic_c_checkers = ['gcc']
let g:syntastic_auto_loc_list=1

"GUI specific stuff
if has("gui_running")
    "add windows key behaviors for guis on any system
    source $VIMRUNTIME/mswin.vim

    "Hide toolbar in gui
    set guioptions-=T

    "Show bottom scroll bar
    set guioptions+=b

    "set window size
    set lines=36
    set columns=120

    "Unix/Linux GUI doesn't change the pwd to the dir of the opened file
    if has("unix")
        autocmd VimEnter * if expand('%') != "" | cd %:h | endif
    endif
endif

"change <leader> to ,
let mapleader=','

"filetype settings
filetype on
filetype plugin on
filetype indent on

"General
set number
set nowrap

"Indenting
set tabstop=4
set shiftwidth=4
set expandtab
set cindent

"Ruby Specific indenting
autocmd Filetype ruby,eruby setlocal tabstop=2 shiftwidth=2
"html specific indenting
autocmd Filetype html setlocal tabstop=2 shiftwidth=2

"Folding
set foldenable
set foldmethod=syntax
set foldcolumn=5
set foldlevel=5

"AutoCompletion
set ofu=syntaxcomplete#Complete
map <F10> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
autocmd InsertLeave * if pumvisible() == 0|pclose|endif "close top window on esc

"Ruby AutoCompletion
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading=1
autocmd FileType ruby,eruby let g:rubycomplete_rails=1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global=1
"autocmd Filetype ruby,eruby let g:SuperTabDefaultCompletionType="<c-x><c-o>"

"Theme
syntax enable
set background=dark
let g:solarized_italic=0
set t_Co=16                 "Helps with display in some terminals
colorscheme solarized
set encoding=utf-8
call togglebg#map("<F9>")   "Toggle light/dark colors with <leader>s
set hlsearch                "highligh searches

"NERDTree
map <F2> :NERDTreeToggle<CR>

"Taglist
map <F3> :TagbarToggle<CR>

"Powerline
set laststatus=2 "Always show the statusline
let g:Powerline_colorscheme = 'solarized256'

"Cleanup trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

