#!/bin/sh

touch $HOME/.aliases.local
touch $HOME/.env.local
touch $HOME/.gitconfig.local
touch $HOME/.psqlrc.local
touch $HOME/.tmux.conf.local
touch $HOME/.vimrc.bundles.local
touch $HOME/.vimrc.local
touch $HOME/.zshrc.local

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugClean! +qa

"$HOME"/.vim/bundle/YouCompleteMe/install.py --clang-completer --java-completer

cd "$HOME/.vim/bundle/ctrlp-cmatcher"
CFLAGS=-Qunused-arguments \
CPPFLAGS=-Qunused-arguments \
./install.sh

repoman clone -v

reset -Q

# detect old OS X broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

  cat <<MSG >&2
Warning: \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  sudo mv /etc/{zshenv,zprofile}
(called from ${dir}/post-up:${LINENO})
MSG
fi
