
export JAVA_HOME=/usr/local/java/jdk1.7.0_17
export HADOOP_INSTALL=/home/jon/Developer/lib/hadoop-1.1.2
export HEROKU_PATH=/usr/local/heroku

export PATH=$PATH:$JAVA_HOME/bin:$HADOOP_INSTALL/bin:$HADOOP_INSTALL/sbin:$HEROKU_PATH/bin:/home/jon/Developer/bin:/home/jon/Developer/lib/sbt/bin
export LD_LIBRARY_PATH=/home/jon/Developer/lib
#export C_INCLUDE_PATH=/home/jon/Developer/include

